//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///
        ///	&lt;brick&gt;
        ///
        ///		&lt;x&gt;470&lt;/x&gt;
        ///		&lt;y&gt;99&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;red&lt;/colour&gt;
        ///&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///
        ///		&lt;x&gt;409&lt;/x&gt;
        ///		&lt;y&gt;156&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;red&lt;/colour&gt;
        ///&lt;/brick&gt;
        ///
        ///	&lt;brick&gt;
        ///
        ///		&lt;x&gt;336&lt;/x&gt;
        ///		&lt;y&gt;261&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;red&lt;/colour&gt;
        ///	&lt;/brick&gt;
        ///&lt;brick&gt;
        ///		&lt;x&gt;269&lt;/x&gt;
        ///		&lt;y&gt;325&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;red&lt;/colour&gt;
        ///&lt;/brick&gt;
        ///&lt;brick&gt;
        ///		&lt;x&gt;313&lt;/x&gt;
        ///		&lt;y&gt;171&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;colour&gt;red&lt;/colour&gt;
        ///&lt;/brick&gt;
        ///&lt;brick&gt;
        ///	&lt;x&gt;398&lt;/x&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///    &lt;Block x=&quot;273&quot; y=&quot;208&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;326&quot; y=&quot;208&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;379&quot; y=&quot;208&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;273&quot; y=&quot;231&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;273&quot; y=&quot;254&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;273&quot; y=&quot;277&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;273&quot; y=&quot;300&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;326&quot; y=&quot;323&quot; color=&quot;DarkBlue&quot; hp=&quot;1&quot; /&gt;
        ///	&lt;Block x=&quot;379&quot; y=&quot;323&quot; color=&quot;DarkBlue&quot; hp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
    }
}
